# Generated by Django 3.0.7 on 2020-06-06 04:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compose',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('image', models.ImageField(default='', upload_to='images/')),
                ('compose_date', models.DateField(auto_now=True, verbose_name='compose_date')),
                ('composer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='composer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
